-- 코드를 입력하세요
SELECT L.FOOD_TYPE, L.REST_ID, L.REST_NAME, L.FAVORITES
FROM REST_INFO AS L
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS R ON L.FOOD_TYPE = R.FOOD_TYPE AND L.FAVORITES = R.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;