-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
JOIN (
    SELECT ANIMAL_ID, DATETIME AS OUTS
    FROM ANIMAL_OUTS
) AS R USING (ANIMAL_ID)
ORDER BY TIMESTAMPDIFF(MINUTE,DATETIME,OUTS) DESC LIMIT 2;