-- 코드를 입력하세요
SELECT CATEGORY, SUM(TOTAL_SALES)
FROM BOOK AS L
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) AS R USING (BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY;
